#!/bin/bash -e
# -*- coding: UTF-8 -*-

SCRIPT_DIR=$(dirname $0)

# for dev
if [[ -d "$SCRIPT_DIR/../python/mechanic2/" ]]; then
  export PYTHONPATH=$PYTHONPATH:$SCRIPT_DIR/../python/
fi

if [[ -d "$MECHANIC2_ROOT_DIR/usr/local/mechanic2/lib/" ]]; then
  export PYTHONPATH="$PYTHONPATH:$MECHANIC2_ROOT_DIR/usr/local/mechanic2/lib/"
fi

export PYTHONDONTWRITEBYTECODE=dontdothis

/usr/bin/python2.7 -B -m mechanic2 $*
